import { Router } from 'express';
import { getDb } from '../database.js';

const router = Router();

const rateLimitMap = new Map();

function checkRateLimit(address) {
  const now = Date.now();
  const windowMs = 3600000;
  const maxRequests = 5;

  if (!rateLimitMap.has(address)) {
    rateLimitMap.set(address, { count: 1, resetAt: now + windowMs });
    return { allowed: true, remaining: 4 };
  }

  const entry = rateLimitMap.get(address);
  if (now > entry.resetAt) {
    rateLimitMap.set(address, { count: 1, resetAt: now + windowMs });
    return { allowed: true, remaining: 4 };
  }

  if (entry.count >= maxRequests) {
    return { allowed: false, remaining: 0, retryAfter: Math.ceil((entry.resetAt - now) / 1000) };
  }

  entry.count++;
  return { allowed: true, remaining: maxRequests - entry.count };
}

router.post('/summary', (req, res) => {
  const db = getDb();
  const { address } = req.body;
  if (!address) {
    return res.status(400).json({ error: 'address required' });
  }

  const rateCheck = checkRateLimit(address);
  if (!rateCheck.allowed) {
    return res.status(429).json({
      error: 'Rate limit exceeded. Try again later.',
      retryAfter: rateCheck.retryAfter,
    });
  }

  const cached = db.prepare(
    'SELECT * FROM ai_summaries WHERE address = ? AND generated_at > (unixepoch() - 86400)'
  ).get(address);

  if (cached) {
    return res.json({
      address: cached.address,
      summary: cached.summary,
      generatedAt: new Date(cached.generated_at * 1000).toISOString(),
      model: cached.model,
      disclaimer: 'This summary was generated by AI and may not be complete. Always do your own research.',
    });
  }

  const profile = db.prepare('SELECT * FROM profiles WHERE address = ?').get(address);
  if (!profile) {
    return res.status(404).json({ error: 'Profile not found. Create a profile first.' });
  }

  const portfolio = db.prepare('SELECT * FROM portfolio_items WHERE address = ? ORDER BY year DESC').all(address);

  const prompt = `Based on the following information, produce a 3-sentence credibility summary. Be neutral and factual. If the information is limited, state that candidly.

Name/Handle: ${profile.username || 'Unnamed'}
Stacks Address: ${address}
Bio: ${profile.bio || 'No bio provided'}
Portfolio Projects: ${portfolio.map(p => p.title).join(', ') || 'None provided yet'}

Produce exactly 3 sentences covering: professional background, notable achievements, and any observations.`;

  const apiKey = process.env.OPENAI_API_KEY;
  const aiProvider = process.env.AI_PROVIDER || 'openai';

  if (!apiKey) {
    const fallback = `This user has been active in the creative economy. Based on their profile, they have ${portfolio.length} portfolio item(s). Connect with them to learn more about their work.`;
    try {
      db.prepare('INSERT OR REPLACE INTO ai_summaries (address, summary, model, generated_at) VALUES (?, ?, ?, unixepoch())')
        .run(address, fallback, 'fallback');
    } catch (_) { }
    return res.json({
      address,
      summary: fallback,
      generatedAt: new Date().toISOString(),
      model: 'fallback',
      disclaimer: 'AI credibility summaries will be available post-launch. Review on-chain reputation instead.',
    });
  }

  generateAISummary(apiKey, aiProvider, prompt)
    .then(({ summary, model }) => {
      db.prepare('INSERT OR REPLACE INTO ai_summaries (address, summary, model, generated_at) VALUES (?, ?, ?, unixepoch())')
        .run(address, summary, model);
      res.json({
        address,
        summary,
        generatedAt: new Date().toISOString(),
        model,
        disclaimer: 'This summary was generated by AI and may not be complete. Always do your own research.',
      });
    })
    .catch((err) => {
      console.error('AI summary generation failed:', err.message);
      res.status(500).json({ error: 'Failed to generate AI summary. Try again later.' });
    });
});

async function generateAISummary(apiKey, provider, prompt) {
  if (provider === 'openai') {
    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model: 'gpt-4',
        messages: [
          { role: 'system', content: 'You are a neutral credibility assessment assistant for a creative economy platform. You produce concise, factual summaries.' },
          { role: 'user', content: prompt },
        ],
        max_tokens: 150,
        temperature: 0.3,
      }),
    });

    if (!response.ok) {
      throw new Error(`OpenAI API error: ${response.status}`);
    }

    const data = await response.json();
    return { summary: data.choices[0].message.content.trim(), model: 'gpt-4' };
  }

  if (provider === 'anthropic') {
    const response = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': apiKey,
        'anthropic-version': '2023-06-01',
      },
      body: JSON.stringify({
        model: 'claude-3-haiku-20240307',
        max_tokens: 150,
        system: 'You are a neutral credibility assessment assistant for a creative economy platform. You produce concise, factual summaries.',
        messages: [{ role: 'user', content: prompt }],
      }),
    });

    if (!response.ok) {
      throw new Error(`Anthropic API error: ${response.status}`);
    }

    const data = await response.json();
    return { summary: data.content[0].text.trim(), model: 'claude-3-haiku' };
  }

  throw new Error(`Unknown AI provider: ${provider}`);
}

export default router;
