import { Router } from 'express';
import { getDb } from '../database.js';

const router = Router();

const rateLimitMap = new Map();

function checkRateLimit(address) {
  const now = Date.now();
  const windowMs = 3600000;
  const maxRequests = 5;
  if (!rateLimitMap.has(address)) {
    rateLimitMap.set(address, { count: 1, resetAt: now + windowMs });
    return { allowed: true, remaining: 4 };
  }
  const entry = rateLimitMap.get(address);
  if (now > entry.resetAt) {
    rateLimitMap.set(address, { count: 1, resetAt: now + windowMs });
    return { allowed: true, remaining: 4 };
  }
  if (entry.count >= maxRequests) return { allowed: false, remaining: 0, retryAfter: Math.ceil((entry.resetAt - now) / 1000) };
  entry.count++;
  return { allowed: true, remaining: maxRequests - entry.count };
}

router.post('/summary', async (req, res, next) => {
  try {
    const db = await getDb();
    const { address } = req.body;
    if (!address) { db.release(); return res.status(400).json({ error: 'address required' }); }
    const rateCheck = checkRateLimit(address);
    if (!rateCheck.allowed) {
      db.release();
      return res.status(429).json({ error: 'Rate limit exceeded. Try again later.', retryAfter: rateCheck.retryAfter });
    }
    const oneDayAgo = Math.floor(Date.now() / 1000) - 86400;
    const cached = await db.get('SELECT * FROM ai_summaries WHERE address = $1 AND generated_at > $2', [address, oneDayAgo]);
    if (cached) {
      db.release();
      return res.json({ address: cached.address, summary: cached.summary, generatedAt: new Date(cached.generated_at * 1000).toISOString(), model: cached.model, disclaimer: 'This summary was generated by AI and may not be complete. Always do your own research.' });
    }
    const profile = await db.get('SELECT * FROM profiles WHERE address = $1', [address]);
    if (!profile) { db.release(); return res.status(404).json({ error: 'Profile not found. Create a profile first.' }); }
    const portfolio = await db.all('SELECT * FROM portfolio_items WHERE address = $1 ORDER BY year DESC', [address]);
    db.release();

    const apiKey = process.env.OPENAI_API_KEY;
    if (!apiKey) {
      const fallback = `This user has been active in the creative economy. Based on their profile, they have ${portfolio.length} portfolio item(s). Connect with them to learn more about their work.`;
      const db2 = await getDb();
      await db2.run('INSERT OR REPLACE INTO ai_summaries (address, summary, model, generated_at) VALUES ($1, $2, $3, $4)', [address, fallback, 'fallback', Math.floor(Date.now() / 1000)]);
      db2.release();
      return res.json({ address, summary: fallback, generatedAt: new Date().toISOString(), model: 'fallback', disclaimer: 'AI credibility summaries will be available post-launch. Review on-chain reputation instead.' });
    }

    const prompt = `Based on the following information, produce a 3-sentence credibility summary. Be neutral and factual. If the information is limited, state that candidly.\n\nName/Handle: ${profile.username || 'Unnamed'}\nStacks Address: ${address}\nBio: ${profile.bio || 'No bio provided'}\nPortfolio Projects: ${portfolio.map(p => p.title).join(', ') || 'None provided yet'}\n\nProduce exactly 3 sentences covering: professional background, notable achievements, and any observations.`;

    try {
      const response = await fetch('https://api.openai.com/v1/chat/completions', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${apiKey}` },
        body: JSON.stringify({ model: 'gpt-4', messages: [{ role: 'system', content: 'You are a neutral credibility assessment assistant for a creative economy platform. You produce concise, factual summaries.' }, { role: 'user', content: prompt }], max_tokens: 150, temperature: 0.3 }),
      });
      if (!response.ok) throw new Error(`OpenAI API error: ${response.status}`);
      const data = await response.json();
      const summary = data.choices[0].message.content.trim();
      const now = Math.floor(Date.now() / 1000);
      const db3 = await getDb();
      await db3.run('INSERT OR REPLACE INTO ai_summaries (address, summary, model, generated_at) VALUES ($1, $2, $3, $4)', [address, summary, 'gpt-4', now]);
      db3.release();
      res.json({ address, summary, generatedAt: new Date().toISOString(), model: 'gpt-4', disclaimer: 'This summary was generated by AI and may not be complete. Always do your own research.' });
    } catch (err) {
      console.error('AI summary generation failed:', err.message);
      res.status(500).json({ error: 'Failed to generate AI summary. Try again later.' });
    }
  } catch (err) { next(err); }
});

export default router;
