/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateCampaignRouteImport } from './routes/create-campaign'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as EndorseRouteImport } from './routes/endorse'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as CampaignIdRouteImport } from './routes/campaign.$id'
import { Route as PortfolioAddRouteImport } from './routes/portfolio.add'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as ProfileEditRouteImport } from './routes/profile.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateCampaignRoute = CreateCampaignRouteImport.update({
  id: '/create-campaign',
  path: '/create-campaign',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const EndorseRoute = EndorseRouteImport.update({
  id: '/endorse',
  path: '/endorse',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignIdRoute = CampaignIdRouteImport.update({
  id: '/campaign/$id',
  path: '/campaign/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioAddRoute = PortfolioAddRouteImport.update({
  id: '/portfolio/add',
  path: '/portfolio/add',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-campaign': typeof CreateCampaignRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/endorse': typeof EndorseRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/campaign/$id': typeof CampaignIdRoute
  '/portfolio/add': typeof PortfolioAddRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-campaign': typeof CreateCampaignRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/endorse': typeof EndorseRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/campaign/$id': typeof CampaignIdRoute
  '/portfolio/add': typeof PortfolioAddRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile': typeof ProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-campaign': typeof CreateCampaignRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/endorse': typeof EndorseRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/campaign/$id': typeof CampaignIdRoute
  '/portfolio/add': typeof PortfolioAddRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-campaign'
    | '/dashboard'
    | '/discover'
    | '/endorse'
    | '/login'
    | '/register'
    | '/campaign/$id'
    | '/portfolio/add'
    | '/profile/edit'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-campaign'
    | '/dashboard'
    | '/discover'
    | '/endorse'
    | '/login'
    | '/register'
    | '/campaign/$id'
    | '/portfolio/add'
    | '/profile/edit'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/create-campaign'
    | '/dashboard'
    | '/discover'
    | '/endorse'
    | '/login'
    | '/register'
    | '/campaign/$id'
    | '/portfolio/add'
    | '/profile/edit'
    | '/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateCampaignRoute: typeof CreateCampaignRoute
  DashboardRoute: typeof DashboardRoute
  DiscoverRoute: typeof DiscoverRoute
  EndorseRoute: typeof EndorseRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  CampaignIdRoute: typeof CampaignIdRoute
  PortfolioAddRoute: typeof PortfolioAddRoute
  ProfileEditRoute: typeof ProfileEditRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-campaign': {
      id: '/create-campaign'
      path: '/create-campaign'
      fullPath: '/create-campaign'
      preLoaderRoute: typeof CreateCampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endorse': {
      id: '/endorse'
      path: '/endorse'
      fullPath: '/endorse'
      preLoaderRoute: typeof EndorseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign/$id': {
      id: '/campaign/$id'
      path: '/campaign/$id'
      fullPath: '/campaign/$id'
      preLoaderRoute: typeof CampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/add': {
      id: '/portfolio/add'
      path: '/portfolio/add'
      fullPath: '/portfolio/add'
      preLoaderRoute: typeof PortfolioAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateCampaignRoute: CreateCampaignRoute,
  DashboardRoute: DashboardRoute,
  DiscoverRoute: DiscoverRoute,
  EndorseRoute: EndorseRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  CampaignIdRoute: CampaignIdRoute,
  PortfolioAddRoute: PortfolioAddRoute,
  ProfileEditRoute: ProfileEditRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
