export const BOS_STATES = Object.freeze({
  DISBURSEMENT_INITIATED: 'disbursement_initiated',
  PREFLIGHT_CHECK: 'preflight_check',
  MANUAL_REVIEW_REQUIRED: 'manual_review_required',
  BURN_SUBMITTED: 'burn_submitted',
  BURN_CONFIRMED: 'burn_confirmed',
  ATTESTATION_REQUESTED: 'attestation_requested',
  ATTESTATION_CONFIRMED: 'attestation_confirmed',
  DESTINATION_RELEASE_SUBMITTED: 'destination_release_submitted',
  DESTINATION_RELEASE_CONFIRMED: 'destination_release_confirmed',
  YELLOWCARD_PAYOUT_SUBMITTED: 'yellowcard_payout_submitted',
  YELLOWCARD_PAYOUT_CONFIRMED: 'yellowcard_payout_confirmed',
  SETTLED: 'settled',
  FAILED: 'failed',
  CANCELLED: 'cancelled',
});

export const TERMINAL_STATES = new Set([
  BOS_STATES.SETTLED,
  BOS_STATES.FAILED,
  BOS_STATES.CANCELLED,
]);

export const ACTIVE_STATES = new Set(
  Object.values(BOS_STATES).filter(s => !TERMINAL_STATES.has(s))
);

export const MANUAL_REVIEW_STATES = new Set([
  BOS_STATES.MANUAL_REVIEW_REQUIRED,
]);

export const ERROR_CODES = Object.freeze({
  INIT_FAILED: 'u8201',
  INVALID_CAMPAIGN: 'u8202',
  INVALID_MILESTONE: 'u8203',
  INVALID_AMOUNT: 'u8204',
  MISSING_RECIPIENT: 'u8205',
  DB_ERROR: 'u8206',
  CONFIG_ERROR: 'u8207',
  DUPLICATE_IDEMPOTENCY: 'u8208',
  ADAPTER_UNAVAILABLE: 'u8209',

  BURN_FAILED: 'u8210',
  BURN_TX_FAILED: 'u8211',
  BURN_NOT_CONFIRMED: 'u8212',
  BURN_TIMEOUT: 'u8213',
  INSUFFICIENT_BALANCE: 'u8214',
  INVALID_BURN_TX: 'u8215',
  BURN_REJECTED: 'u8216',
  BURN_NETWORK_ERROR: 'u8217',
  BURN_ALREADY_SUBMITTED: 'u8218',

  ATTESTATION_FAILED: 'u8220',
  ATTESTATION_REJECTED: 'u8221',
  ATTESTATION_TIMEOUT: 'u8222',
  ATTESTATION_NETWORK_ERROR: 'u8223',
  ATTESTATION_INVALID: 'u8224',
  ATTESTATION_ALREADY_CONFIRMED: 'u8225',
  ATTESTATION_EXPIRED: 'u8226',
  ATTESTATION_PENDING_TOO_LONG: 'u8227',
  ATTESTATION_MISMATCH: 'u8228',

  PAYOUT_FAILED: 'u8230',
  PAYOUT_REJECTED: 'u8231',
  PAYOUT_TIMEOUT: 'u8232',
  PAYOUT_NETWORK_ERROR: 'u8233',
  PAYOUT_INVALID_RECIPIENT: 'u8234',
  PAYOUT_AMOUNT_EXCEEDS_LIMIT: 'u8235',
  PAYOUT_DUPLICATE: 'u8236',
  PAYOUT_ALREADY_SUBMITTED: 'u8237',
  PAYOUT_RATE_EXPIRED: 'u8238',

  UNKNOWN_STATE: 'u8290',
  TRANSITION_FORBIDDEN: 'u8291',
  GUARD_REJECTED: 'u8292',
  RETRY_EXHAUSTED: 'u8293',
  MANUAL_REVIEW_REQUIRED_CODE: 'u8294',
  TIMEOUT: 'u8295',
  INTERNAL_ERROR: 'u8296',
});

export const TRANSITIONS = {
  [BOS_STATES.DISBURSEMENT_INITIATED]: [BOS_STATES.PREFLIGHT_CHECK, BOS_STATES.FAILED],
  [BOS_STATES.PREFLIGHT_CHECK]: [BOS_STATES.BURN_SUBMITTED, BOS_STATES.MANUAL_REVIEW_REQUIRED, BOS_STATES.FAILED],
  [BOS_STATES.MANUAL_REVIEW_REQUIRED]: [BOS_STATES.BURN_SUBMITTED, BOS_STATES.FAILED, BOS_STATES.CANCELLED],
  [BOS_STATES.BURN_SUBMITTED]: [BOS_STATES.BURN_CONFIRMED, BOS_STATES.FAILED],
  [BOS_STATES.BURN_CONFIRMED]: [BOS_STATES.ATTESTATION_REQUESTED, BOS_STATES.FAILED],
  [BOS_STATES.ATTESTATION_REQUESTED]: [BOS_STATES.ATTESTATION_CONFIRMED, BOS_STATES.FAILED],
  [BOS_STATES.ATTESTATION_CONFIRMED]: [BOS_STATES.DESTINATION_RELEASE_SUBMITTED, BOS_STATES.FAILED],
  [BOS_STATES.DESTINATION_RELEASE_SUBMITTED]: [BOS_STATES.DESTINATION_RELEASE_CONFIRMED, BOS_STATES.FAILED],
  [BOS_STATES.DESTINATION_RELEASE_CONFIRMED]: [BOS_STATES.YELLOWCARD_PAYOUT_SUBMITTED, BOS_STATES.FAILED],
  [BOS_STATES.YELLOWCARD_PAYOUT_SUBMITTED]: [BOS_STATES.YELLOWCARD_PAYOUT_CONFIRMED, BOS_STATES.FAILED],
  [BOS_STATES.YELLOWCARD_PAYOUT_CONFIRMED]: [BOS_STATES.SETTLED, BOS_STATES.FAILED],
  [BOS_STATES.FAILED]: [BOS_STATES.MANUAL_REVIEW_REQUIRED],
};

export function isValidTransition(from, to) {
  const allowed = TRANSITIONS[from];
  if (!allowed) return false;
  return allowed.includes(to);
}

export function isTerminal(state) {
  return TERMINAL_STATES.has(state);
}

export function isActive(state) {
  return ACTIVE_STATES.has(state);
}
