name: Deploy
on:
  push:
    branches: [main]

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Deploy to Vercel
        env:
          VERCEL_ORG_ID: team_PH6pa81fDqeN5bXrKdiJRLzU
          VERCEL_PROJECT_ID: prj_oDyqNeKh2fOyna3nRLvAGNTAZxWP
        run: vercel deploy --prod --yes --token=${{ secrets.VERCEL_TOKEN }}

  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Deploy backend to Vercel
        env:
          VERCEL_ORG_ID: team_PH6pa81fDqeN5bXrKdiJRLzU
          VERCEL_PROJECT_ID: prj_epPtEBx4ErPk6mfDkgnKSkSn5YmM
        run: vercel deploy --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
