name: Deploy
on:
  push:
    branches: [main]

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Deploy to Vercel
        env:
          VERCEL_ORG_ID: team_PH6pa81fDqeN5bXrKdiJRLzU
          VERCEL_PROJECT_ID: prj_oDyqNeKh2fOyna3nRLvAGNTAZxWP
        run: vercel deploy --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: app

  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy
        run: curl -s -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
